# Generated by Django 6.0.4 on 2026-05-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='donor',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='donation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(max_length=10),
        ),
    ]
