# Generated by Django 6.0.5 on 2026-06-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_donor_age_donor_availability_donor_donation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='ai_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='priority_level',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
